### ISSUE TITLE
Can you provide an example `_prototype.urdf` file?

### ISSUE THREAD

**Issue by ethanabrooks** [cbteeple/object2urdf#1]
Hi, I am new to robotics simulation. I am trying to use this tool to convert the YCB object dataset to a pybullet friendly URDF format. Could you provide an example of the `_propotype.urdf` file that the `build_object_library.py` script requires? Thank you.

**Comment by ethanabrooks** [comment]
I found this : https://github.com/GistNoesis/BrickRegistration/blob/main/_prototype.urdf

I am just interested in the visuals, not the physics, so I'm not picky.

**Comment by cbteeple** [comment]
If you look in the examples folder, there are a few example `_prototype.urdf` files you could reference. Are you looking for something else besides those examples?

**Comment by ethanabrooks** [comment]
No I missed those. It looks like the one I found is identical to at least one of those. Thanks for your help.
